# Install pre-commit hooks via
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2c1f9cf5cb705f73dffe4b21f7c61470ba9 # v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: efd8b1e16f05132acf6edcf2827eeab21e0e00db # frozen: v3.0.0
    hooks:
      - id: prettier
        files: \.(md|rst|yml|yaml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/psf/black
    rev: 193ee766ca496871f93621d6b58d57a6564ff81b # frozen: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 2e74dc4c30c336176e76e0426c66f09a4e79df9c # frozen: 1.15.0
    hooks:
      - id: blacken-docs

  - repo: https://github.com/MarcoGorelli/cython-lint
    rev: 0d4704ff7d75ad487dcde6947c628be824060184 # frozen: v0.15.0
    hooks:
      - id: cython-lint
        args: [--no-pycodestyle, --max-line-length=88]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: ade96e24aa3fa43c9d9b50d6cccae93d82765f40 # frozen: v0.0.282
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/codespell-project/codespell
    rev: "355e50e14fd03fe83e4ed9aa0489824b150b3b58" # frozen: v2.2.5
    hooks:
      - id: codespell
        args: ["-w", "-L", "ans,nd,sav,mke,ags,mot,coo,whos"]
