version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.4

    steps:
      - checkout

      - run:
          name: Install TeX
          command: |
            sudo apt update
            sudo apt install -y \
              dvipng \
              texlive-latex-base \
              texlive-latex-extra

      - restore_cache:
          keys:
            - pip-cache-v1

      - run:
          name: Install Python dependencies
          command: |
            pip install --upgrade --user pip
            pip install --user -r requirements.txt
            pip list

      - save_cache:
          key: pip-cache-v1
          paths:
            - ~/.cache/pip

      - run:
          name: Build docs
          command: |
            # NOTE: bad interaction w/ blas multithreading on circleci
            export OMP_NUM_THREADS=1
            make pdf
            make html  # FIX: check that failing examples produce failure
            cp \
              ScientificPythonLectures.pdf \
              ScientificPythonLectures-simple.pdf \
              build/html/_downloads/

      - store_artifacts:
          path: build/html
